package com.fuxin.app

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.fuxin.app.ui.theme.*

data class FuxinFeature(val id: String, val title: String, val description: String)
data class FuxinModule(val id: String, val marker: String, val title: String, val subtitle: String, val intro: String, val features: List<FuxinFeature>)

internal val modules = listOf(
    FuxinModule("healing", "◌", "自我情感疗愈", "先把自己照顾回来", "当情绪很满，先让自己被听见、被安放。", listOf(
        FuxinFeature("companion", "AI 语言陪聊", "把此刻最想说的话说出来"), FuxinFeature("mood", "情绪落点", "记录此刻的感受和身体反应"), FuxinFeature("diary", "疗愈日记", "把混乱放进一个安全的地方"), FuxinFeature("grounding", "情绪急救", "用 1—5 分钟回到当下"), FuxinFeature("facts", "事实与猜测", "分开发生的事和脑海里的解释"), FuxinFeature("self-worth", "自我价值修复", "把自责改写成具体的自我陈述"), FuxinFeature("life-plan", "生活恢复计划", "从睡眠、饮食和专注开始恢复"), FuxinFeature("supporter", "支持者准备", "整理你想向谁寻求怎样的支持"))),
    FuxinModule("reconciliation", "↗", "寻求复合机会", "想靠近，也先保护自己", "不承诺结果，只帮你看清条件和下一次行动。", listOf(
        FuxinFeature("motivation", "复合动机澄清", "分辨想念、不甘和共同改变"), FuxinFeature("opportunity", "关系机会评估", "看安全、尊重和修复基础"), FuxinFeature("relation-facts", "关系事实卡", "记录原因、改变、问题和底线"), FuxinFeature("communication-goal", "沟通目标选择", "一次沟通只做一件事"), FuxinFeature("draft", "AI 消息草稿", "生成清晰、低压力的表达"), FuxinFeature("risk-check", "消息风险检查", "发送前检查指责和隐性施压"), FuxinFeature("cooling", "72 小时冷却", "把决定留给更平静的自己"), FuxinFeature("outcome", "沟通结果记录", "只记录事实，不急着下结论"), FuxinFeature("boundaries", "拒绝与边界处理", "尊重对方，也保护自己"))),
    FuxinModule("detachment", "⌁", "戒断", "把注意力慢慢还给自己", "不靠责备自己，先把触发到冲动之间的距离拉长。", listOf(
        FuxinFeature("detachment-goal", "戒断目标", "从 24 小时或 3 天开始尝试"), FuxinFeature("trigger", "触发源识别", "找到最常让你想查看的东西"), FuxinFeature("urge-delay", "冲动延迟", "先和冲动相处 5、15 或 30 分钟"), FuxinFeature("urge-log", "冲动记录", "看见触发和行动之间的规律"), FuxinFeature("unsent", "不发送保管箱", "想说的话先保存，不需要送达"), FuxinFeature("alternatives", "替代行动", "为冲动准备另一个出口"), FuxinFeature("necessary-contact", "必要联系模式", "只处理共同事务和明确边界"), FuxinFeature("relapse", "复发复盘", "把一次复发变成下一次预案"), FuxinFeature("detachment-plan", "每日戒断计划", "今天最多完成三个小动作"))))

private enum class Tab { TOOLS, RECORDS, MINE }
private enum class Page { HOME, MODULE, FEATURE, DIAGNOSIS, RECORDS, MINE }

@Composable private fun Text(text: String, color: Color = Color.Unspecified, modifier: Modifier = Modifier, fontSize: androidx.compose.ui.unit.TextUnit = androidx.compose.ui.unit.TextUnit.Unspecified, fontWeight: FontWeight? = null, letterSpacing: androidx.compose.ui.unit.TextUnit = androidx.compose.ui.unit.TextUnit.Unspecified, lineHeight: androidx.compose.ui.unit.TextUnit = androidx.compose.ui.unit.TextUnit.Unspecified, maxLines: Int = Int.MAX_VALUE) {
    androidx.compose.material3.Text(text, color = color, modifier = modifier, fontSize = fontSize, fontWeight = fontWeight, letterSpacing = letterSpacing, lineHeight = lineHeight, maxLines = maxLines)
}

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); enableEdgeToEdge(); setContent { 抚心Theme { FuxinApp() } } }
}

@Composable fun FuxinApp() {
    var tab by rememberSaveable { mutableStateOf(Tab.TOOLS) }; var page by rememberSaveable { mutableStateOf(Page.HOME) }
    var selectedModule by rememberSaveable { mutableStateOf("healing") }; var selectedFeature by rememberSaveable { mutableStateOf("companion") }
    Surface(Modifier.fillMaxSize(), color = Night) { Scaffold(containerColor = Night, bottomBar = {
        if (page == Page.HOME || page == Page.RECORDS || page == Page.MINE) NavigationBar(containerColor = SurfaceNight) {
            Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceEvenly) {
                NavItem("工具", "✦", tab == Tab.TOOLS, Modifier.weight(1f)) { tab = Tab.TOOLS; page = Page.HOME }
                NavItem("记录", "◌", tab == Tab.RECORDS, Modifier.weight(1f)) { tab = Tab.RECORDS; page = Page.RECORDS }
                NavItem("我的", "○", tab == Tab.MINE, Modifier.weight(1f)) { tab = Tab.MINE; page = Page.MINE }
            }
        }
    }) { inset -> Box(Modifier.padding(inset)) { when (page) {
        Page.HOME -> HomePage({ selectedModule = it; page = Page.MODULE }, { page = Page.DIAGNOSIS })
        Page.MODULE -> ModulePage(selectedModule, { page = Page.HOME }, { selectedFeature = it; page = Page.FEATURE }, { page = Page.DIAGNOSIS })
        Page.FEATURE -> FeaturePage(selectedModule, selectedFeature) { page = Page.MODULE }
        Page.DIAGNOSIS -> DiagnosisPage({ page = Page.HOME }, { selectedModule = it; page = Page.MODULE })
        Page.RECORDS -> RecordsPage { tab = Tab.TOOLS; page = Page.HOME }; Page.MINE -> MinePage { tab = Tab.TOOLS; page = Page.HOME }
    } } } }
}

@Composable private fun NavItem(label: String, icon: String, selected: Boolean, modifier: Modifier = Modifier, click: () -> Unit) { Column(modifier.clip(RoundedCornerShape(14.dp)).clickable { click() }.padding(vertical = 7.dp), horizontalAlignment = Alignment.CenterHorizontally) { Text(icon, if (selected) Coral else TextDim, fontSize = 22.sp); Text(label, if (selected) WarmWhite else TextDim, fontSize = 11.sp, fontWeight = if (selected) FontWeight.Bold else FontWeight.Normal) } }

@Composable private fun Brand() { Row(verticalAlignment = Alignment.CenterVertically) { Box(Modifier.size(38.dp).clip(RoundedCornerShape(13.dp)).background(Brush.linearGradient(listOf(Coral, Orange))), contentAlignment = Alignment.Center) { Text("心", Night, fontSize = 18.sp, fontWeight = FontWeight.Black) }; Text("FUXIN", WarmWhite, fontSize = 14.sp, fontWeight = FontWeight.Bold, letterSpacing = 3.sp, modifier = Modifier.padding(start = 11.dp)) } }

@Composable private fun EmotionArt(color: Color, compact: Boolean = false) { Canvas(Modifier.size(if (compact) 76.dp else 142.dp)) { val c = Offset(size.width * .56f, size.height * .45f); drawCircle(Brush.radialGradient(listOf(color.copy(alpha = .9f), color.copy(alpha = .06f), Color.Transparent), c, size.minDimension * .72f), size.minDimension * .72f, c); drawArc(color, 215f, 235f, false, c - Offset(size.minDimension * .33f, size.minDimension * .33f), Size(size.minDimension * .66f, size.minDimension * .66f), style = Stroke(size.minDimension * .035f, cap = StrokeCap.Round)); drawArc(ElectricYellow.copy(alpha = .8f), 28f, 150f, false, c - Offset(size.minDimension * .21f, size.minDimension * .21f), Size(size.minDimension * .42f, size.minDimension * .42f), style = Stroke(size.minDimension * .035f, cap = StrokeCap.Round)); drawCircle(WarmWhite, size.minDimension * .045f, c) } }

@Composable private fun HomePage(openModule: (String) -> Unit, openDiagnosis: () -> Unit) { LazyColumn(Modifier.fillMaxSize().padding(horizontal = 20.dp), contentPadding = PaddingValues(top = 24.dp, bottom = 32.dp)) { item { Brand(); Spacer(Modifier.height(28.dp)); Card(colors = CardDefaults.cardColors(containerColor = SurfaceNight), shape = RoundedCornerShape(30.dp), modifier = Modifier.fillMaxWidth()) { Box(Modifier.fillMaxWidth().background(Brush.linearGradient(listOf(Color(0xFF321A32), Color(0xFF1C1725)))).padding(22.dp)) { Column { Text("TODAY / 现在", Coral, fontSize = 11.sp, fontWeight = FontWeight.Bold, letterSpacing = 2.sp); Text("情绪很满的时候，\n先站回自己这一边。", WarmWhite, fontSize = 28.sp, fontWeight = FontWeight.Black, lineHeight = 36.sp, modifier = Modifier.padding(top = 12.dp)); Text("不用立刻决定关系。先做一个让你轻一点的动作。", TextMuted, fontSize = 13.sp, lineHeight = 20.sp, modifier = Modifier.padding(top = 10.dp)); Button(onClick = openDiagnosis, colors = ButtonDefaults.buttonColors(containerColor = Coral, contentColor = Night), shape = RoundedCornerShape(16.dp), modifier = Modifier.fillMaxWidth().padding(top = 20.dp).height(52.dp)) { Text("开始关系自诊  →", fontWeight = FontWeight.Bold) } }; EmotionArt(Orange, true) } }; Row(Modifier.fillMaxWidth().padding(top = 25.dp, bottom = 14.dp), horizontalArrangement = Arrangement.SpaceBetween) { Text("或者，直接选择你现在需要的", TextMuted, fontSize = 13.sp); Text("3 个方向", ElectricYellow, fontSize = 13.sp, fontWeight = FontWeight.Bold) } }; items(modules) { ModuleCard(it) { openModule(it.id) } }; item { Spacer(Modifier.height(22.dp)); Text("不评判你的选择  ·  不自动发送  ·  记录只属于你", TextDim, fontSize = 11.sp); Text("抚心是 AI 关系支持工具，不替代心理咨询或医疗诊断。", TextDim, fontSize = 10.sp, modifier = Modifier.padding(top = 9.dp)) } } }

@Composable private fun ModuleCard(module: FuxinModule, click: () -> Unit) { val color = moduleColor(module.id); Card(colors = CardDefaults.cardColors(containerColor = SurfaceNight), shape = RoundedCornerShape(24.dp), modifier = Modifier.fillMaxWidth().padding(vertical = 7.dp).clickable { click() }) { Column(Modifier.padding(18.dp)) { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.Top) { Column(Modifier.weight(1f)) { Text("${module.marker}  ${module.title}", WarmWhite, fontSize = 20.sp, fontWeight = FontWeight.Bold); Text(module.subtitle, color, fontSize = 12.sp, fontWeight = FontWeight.Bold, modifier = Modifier.padding(top = 5.dp)) }; EmotionArt(color, true) }; Text(module.intro, TextMuted, fontSize = 13.sp, lineHeight = 19.sp, modifier = Modifier.padding(top = 4.dp)); Row(Modifier.padding(top = 16.dp), verticalAlignment = Alignment.CenterVertically) { Text("${module.features.size} 个工具  ·  约 5 分钟", TextDim, fontSize = 11.sp); Spacer(Modifier.weight(1f)); Button(onClick = click, colors = ButtonDefaults.buttonColors(containerColor = color, contentColor = Night), contentPadding = PaddingValues(horizontal = 16.dp), shape = RoundedCornerShape(12.dp), modifier = Modifier.height(40.dp)) { Text("直接开始", fontSize = 12.sp, fontWeight = FontWeight.Bold) } } } } }

@Composable private fun ModulePage(moduleId: String, back: () -> Unit, openFeature: (String) -> Unit, diagnosis: () -> Unit) { val module = modules.first { it.id == moduleId }; val color = moduleColor(moduleId); Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal = 20.dp)) { Text("‹  ${module.title}", TextMuted, fontSize = 17.sp, modifier = Modifier.padding(top = 22.dp).clickable { back() }); Card(colors = CardDefaults.cardColors(containerColor = SurfaceNight), shape = RoundedCornerShape(28.dp), modifier = Modifier.fillMaxWidth().padding(top = 22.dp)) { Row(Modifier.padding(20.dp), verticalAlignment = Alignment.CenterVertically) { Column(Modifier.weight(1f)) { Text("${module.marker}  ${module.subtitle}", color, fontSize = 12.sp, fontWeight = FontWeight.Bold); Text(module.intro, WarmWhite, fontSize = 24.sp, fontWeight = FontWeight.Black, lineHeight = 31.sp, modifier = Modifier.padding(top = 10.dp)) }; EmotionArt(color, true) } }; Text("TODAY / 今天先做这一件事", ElectricYellow, fontSize = 11.sp, fontWeight = FontWeight.Bold, letterSpacing = 1.sp, modifier = Modifier.padding(top = 28.dp)); Button(onClick = { openFeature(module.features.first().id) }, colors = ButtonDefaults.buttonColors(containerColor = color, contentColor = Night), shape = RoundedCornerShape(16.dp), modifier = Modifier.fillMaxWidth().padding(top = 10.dp).height(56.dp)) { Text("${module.features.first().title}  →", fontSize = 16.sp, fontWeight = FontWeight.Bold) }; Text("功能工具", WarmWhite, fontSize = 20.sp, fontWeight = FontWeight.Bold, modifier = Modifier.padding(top = 30.dp, bottom = 10.dp)); module.features.chunked(2).forEach { pair -> Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(10.dp)) { pair.forEach { feature -> ToolCard(feature, color, Modifier.weight(1f)) { openFeature(feature.id) } }; if (pair.size == 1) Spacer(Modifier.weight(1f)) } }; OutlinedButton(onClick = diagnosis, shape = RoundedCornerShape(14.dp), modifier = Modifier.fillMaxWidth().padding(top = 24.dp).height(48.dp)) { Text("不确定？重新帮我找方向", TextMuted) }; Spacer(Modifier.height(30.dp)) } }

@Composable private fun ToolCard(feature: FuxinFeature, color: Color, modifier: Modifier = Modifier, click: () -> Unit) { Card(colors = CardDefaults.cardColors(containerColor = SurfaceNight), shape = RoundedCornerShape(18.dp), modifier = modifier.padding(vertical = 5.dp).clickable { click() }) { Column(Modifier.padding(14.dp).height(94.dp)) { Text("✦", color, fontSize = 18.sp); Text(feature.title, WarmWhite, fontSize = 14.sp, fontWeight = FontWeight.Bold, modifier = Modifier.padding(top = 8.dp)); Text(feature.description, TextDim, fontSize = 10.sp, maxLines = 1, modifier = Modifier.padding(top = 4.dp)) } } }

@Composable private fun FeaturePage(moduleId: String, featureId: String, back: () -> Unit) { val feature = modules.first { it.id == moduleId }.features.firstOrNull { it.id == featureId } ?: modules.first().features.first(); var input by rememberSaveable { mutableStateOf("") }; var selected by rememberSaveable { mutableStateOf("") }; var saved by rememberSaveable { mutableStateOf(false) }; val options = featureOptions(featureId); Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal = 20.dp)) { Text("‹  返回模块", TextMuted, fontSize = 17.sp, modifier = Modifier.padding(top = 22.dp).clickable { back() }); Text("抚心 · 小功能", Coral, fontSize = 11.sp, fontWeight = FontWeight.Bold, letterSpacing = 1.5.sp, modifier = Modifier.padding(top = 34.dp)); Text(feature.title, WarmWhite, fontSize = 29.sp, fontWeight = FontWeight.Black, modifier = Modifier.padding(top = 10.dp)); Text(feature.description, TextMuted, fontSize = 14.sp, modifier = Modifier.padding(top = 7.dp)); Card(colors = CardDefaults.cardColors(containerColor = SurfaceNight), shape = RoundedCornerShape(22.dp), modifier = Modifier.fillMaxWidth().padding(top = 28.dp)) { Column(Modifier.padding(18.dp)) { Text(featurePrompt(featureId), WarmWhite, fontSize = 17.sp, fontWeight = FontWeight.Bold); options.forEach { option -> OptionRow(option, selected == option) { selected = option } }; if (options.isEmpty() || featureId in textFeatures) OutlinedTextField(input, { input = it }, Modifier.fillMaxWidth().height(170.dp).padding(top = 14.dp), placeholder = { Text("写下你的想法……", color = TextDim) }, colors = OutlinedTextFieldDefaults.colors(focusedBorderColor = Coral, unfocusedBorderColor = DividerNight, focusedTextColor = WarmWhite, unfocusedTextColor = WarmWhite, cursorColor = Coral)) } }; Button(onClick = { saved = true }, colors = ButtonDefaults.buttonColors(containerColor = Coral, contentColor = Night), shape = RoundedCornerShape(16.dp), modifier = Modifier.fillMaxWidth().padding(top = 22.dp).height(56.dp)) { Text(if (saved) "已保存 ✓" else "保存这次记录", fontWeight = FontWeight.Bold) }; if (saved) Text("已保存到你的记录中 · 可以随时删除", ElectricYellow, fontSize = 12.sp, modifier = Modifier.padding(top = 15.dp)); Spacer(Modifier.height(30.dp)) } }

@Composable private fun OptionRow(option: String, selected: Boolean, click: () -> Unit) { Row(Modifier.fillMaxWidth().padding(top = 12.dp).clip(RoundedCornerShape(13.dp)).background(if (selected) Color(0xFF49212A) else Color.Transparent).border(1.dp, if (selected) Coral else DividerNight, RoundedCornerShape(13.dp)).clickable { click() }.padding(14.dp), verticalAlignment = Alignment.CenterVertically) { Text(if (selected) "●" else "○", if (selected) Coral else TextDim, modifier = Modifier.width(27.dp)); Text(option, if (selected) WarmWhite else TextMuted, fontSize = 13.sp) } }

@Composable private fun DiagnosisPage(back: () -> Unit, openModule: (String) -> Unit) { var selected by rememberSaveable { mutableStateOf("") }; val options = listOf("我现在更需要先照顾自己" to "healing", "我想了解是否值得尝试沟通" to "reconciliation", "我想减少查看和联系" to "detachment", "我还说不清" to "healing"); Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(horizontal = 20.dp)) { Text("×", TextMuted, fontSize = 28.sp, modifier = Modifier.padding(top = 22.dp).clickable { back() }); Text("关系自诊 · 可选", Coral, fontSize = 11.sp, fontWeight = FontWeight.Bold, letterSpacing = 1.5.sp, modifier = Modifier.padding(top = 34.dp)); Text("先不用做决定。\n看看你此刻最需要什么。", WarmWhite, fontSize = 29.sp, fontWeight = FontWeight.Black, lineHeight = 38.sp, modifier = Modifier.padding(top = 12.dp)); Text("抚心只给你一个起点，不替你决定关系。", TextMuted, fontSize = 13.sp, modifier = Modifier.padding(top = 11.dp)); Text("现在最想改善什么？", WarmWhite, fontSize = 18.sp, fontWeight = FontWeight.Bold, modifier = Modifier.padding(top = 34.dp)); options.forEach { (label, _) -> OptionRow(label, selected == label) { selected = label } }; Button(onClick = { openModule(options.firstOrNull { it.first == selected }?.second ?: "healing") }, enabled = selected.isNotBlank(), colors = ButtonDefaults.buttonColors(containerColor = Coral, contentColor = Night, disabledContainerColor = SurfaceRaised, disabledContentColor = TextDim), shape = RoundedCornerShape(16.dp), modifier = Modifier.fillMaxWidth().padding(top = 25.dp).height(56.dp)) { Text("给我一个起点  →", fontWeight = FontWeight.Bold) }; TextButton(onClick = back, modifier = Modifier.padding(top = 5.dp)) { Text("跳过，直接浏览三个专区", TextMuted) } } }

@Composable private fun RecordsPage(back: () -> Unit) { Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp)) { Text("记录", WarmWhite, fontSize = 30.sp, fontWeight = FontWeight.Black, modifier = Modifier.padding(top = 25.dp)); Text("只给自己看的变化轨迹。", TextMuted, fontSize = 14.sp, modifier = Modifier.padding(top = 8.dp)); Card(colors = CardDefaults.cardColors(containerColor = SurfaceNight), shape = RoundedCornerShape(22.dp), modifier = Modifier.fillMaxWidth().padding(top = 25.dp)) { Column(Modifier.padding(22.dp), horizontalAlignment = Alignment.CenterHorizontally) { EmotionArt(ElectricPurple); Text("这里还没有记录", WarmWhite, fontSize = 18.sp, fontWeight = FontWeight.Bold, modifier = Modifier.padding(top = 8.dp)); Text("完成一个小功能后，它会出现在这里。", TextMuted, fontSize = 13.sp, modifier = Modifier.padding(top = 7.dp)) } }; TextButton(onClick = back, modifier = Modifier.padding(top = 18.dp)) { Text("回到工具  →", Coral) } } }

@Composable private fun MinePage(back: () -> Unit) { Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp)) { Brand(); Text("我的空间", WarmWhite, fontSize = 30.sp, fontWeight = FontWeight.Black, modifier = Modifier.padding(top = 35.dp)); Text("游客模式 · 数据优先保存在本机", TextMuted, fontSize = 14.sp, modifier = Modifier.padding(top = 8.dp)); Card(colors = CardDefaults.cardColors(containerColor = SurfaceNight), shape = RoundedCornerShape(22.dp), modifier = Modifier.fillMaxWidth().padding(top = 25.dp)) { Column(Modifier.padding(20.dp)) { Text("●  本机数据保护中", ElectricYellow, fontSize = 15.sp, fontWeight = FontWeight.Bold); Text("查看、导出或删除你主动提供的内容。", TextMuted, fontSize = 13.sp, modifier = Modifier.padding(top = 10.dp)); HorizontalDivider(color = DividerNight, modifier = Modifier.padding(vertical = 17.dp)); Text("AI 不替代心理咨询或医疗诊断。\n不读取第三方平台，不自动发送。", TextMuted, fontSize = 13.sp, lineHeight = 20.sp) } }; TextButton(onClick = back, modifier = Modifier.padding(top = 18.dp)) { Text("返回工具  →", Coral) } } }

private fun moduleColor(id: String) = when (id) { "healing" -> Coral; "reconciliation" -> Orange; else -> ElectricPurple }
private val textFeatures = setOf("companion", "diary", "draft", "risk-check", "unsent", "supporter", "necessary-contact", "facts", "relation-facts", "relapse")
private fun featurePrompt(id: String) = when (id) { "companion" -> "此刻，你最想说些什么？"; "mood" -> "此刻的情绪和强度"; "opportunity" -> "目前是否仍有基本尊重和沟通空间？"; "urge-delay" -> "你想把这次冲动延迟多久？"; else -> "从这里开始" }
private fun featureOptions(id: String): List<String> = when (id) { "mood" -> listOf("难过", "思念", "愤怒", "焦虑", "麻木", "平静"); "grounding" -> listOf("4-6 呼吸", "五感落地", "暂停联系", "转移注意力"); "motivation" -> listOf("仍然爱着对方", "害怕失去", "孤独和想念", "不甘心结束", "愿意共同改变"); "opportunity" -> listOf("是，仍有基本沟通", "不确定，需要更多事实", "不是，已明确拒绝或不安全"); "communication-goal" -> listOf("了解近况", "表达我的改变", "请求一次见面", "寻求明确答复"); "cooling" -> listOf("保存并开始冷却", "重新修改后再看", "决定不发送"); "outcome" -> listOf("愿意继续沟通", "回复但需要空间", "没有回复", "明确拒绝", "我决定暂停联系"); "detachment-goal" -> listOf("24 小时", "3 天", "7 天", "自定义"); "trigger" -> listOf("照片或聊天记录", "社交媒体动态", "某个地点或时间", "孤独或难过", "相似的事物"); "urge-delay" -> listOf("5 分钟", "15 分钟", "30 分钟"); "urge-log" -> listOf("成功延迟了", "查看了但没有联系", "联系了对方", "转去做替代行动"); "alternatives" -> listOf("出门走 10 分钟", "洗澡或喝水", "联系支持我的人", "做 5 分钟专注任务", "睡前放松"); "boundaries" -> listOf("写一条体面结束的回复", "停止继续追问", "处理被拒绝后的情绪", "转入戒断计划"); "detachment-plan" -> listOf("完成一次冲动延迟", "整理一个触发源", "做一个生活恢复动作", "写下不发送的话"); else -> emptyList() }
